- name: launch instances
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    port: 5986
    ami_id: ami-05d4d7cb4af8b0767
    instance_os: windows
  roles:
    - aws_multi_instances
