---

- name: configure tower hosts
  hosts: "{{ target_tower }}"
  vars:
    create_preload_data: false
  roles:
    - role: tower_install

- name: backup tower
  hosts: "{{ source_tower }}"
  roles:
    - role: tower_backup

- name: restore tower
  hosts: "{{ target_tower }}"
  roles:
    - role: tower_restore
