---

- name: find ami
  ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "{{ instance_info[os].owners }}"
    filters:
      name: "{{ instance_info[os].filter }}"
      architecture: "{{ instance_info[os].architecture }}"
  register: amis

- name: get latest ami image details
  set_fact:
    ami: "{{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"

- name: get latest ami id
  set_fact:
    ami_id: "{{ ami.image_id }}"
