---

- name: install pre-reqs
  yum:
    name:
      - python3
    state: installed

- name: get latest pip
  pip:
    virtualenv: /home/gitlab-runner/ansible_venv
    virtualenv_command: python3 -m venv 
    name: pip
    state: latest

- name: pip install bits
  pip:
    virtualenv: /home/gitlab-runner/ansible_venv
    virtualenv_command: python3 -m venv 
    name:
    - ansible==2.9.19
    - ansible-lint==5.0.1
    - molecule==3.2.3
    - molecule-podman==0.3.0
    - openshift==0.11.2
    - pyvmomi==6.7.3
    - netaddr==0.7.19
    extra_args: --ignore-installed PyYAML
