---


- name: include ansible
  include_tasks: ansible.yml

- name: include ansible for ec2-user
  include_tasks: ec2-user_ansible.yml

- name: include runner
  include_tasks: runner.yml

- name: include podman
  include_tasks: podman.yml
