---

- name: get runner yum repo file
  get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/config_file.repo?os=redhatenterpriseserver&dist=8&source=script"
    dest: /etc/yum.repos.d/runner_gitlab-runner.repo

- name: install gitlab-runner
  yum:
    name: gitlab-runner
    state: installed
  register: install_runner

- name: fix permissions in /home/gitlab-runner
  file:
    path: /home/gitlab-runner
    mode: 0755
    owner: gitlab-runner
    group: gitlab-runner

- name: register runner
  command: "gitlab-runner register --non-interactive --url https://gitlab.com/ --registration-token {{ gitlab_runner_token }} --description {{ inventory_hostname }} --executor shell --tag-list ansible --run-untagged true"
  notify: 
    - restart gitlab-runner
  when: install_runner is changed

- name: ensure runner is running and started
  service:
    name: gitlab-runner
    enabled: true
    state: started
